#!/bin/bash

pacman -S wget sudo --noconfirm

pacman -Syyu

wget -q -O chaotic-AUR-installer.bash https://raw.githubusercontent.com/SharafatKarim/chaotic-AUR-installer/main/install.bash && sudo bash chaotic-AUR-installer.bash && rm chaotic-AUR-installer.bash

pacman -Syyu
