#!/bin/bash


echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf

pacman -S reflector

reflector -c "IN" -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist

echo 'Server = https://geo.mirror.pkgbuild.com/$repo/os/$arch'  >> /etc/pacman.d/mirrorlist


pacman -Syyu

pacman -S nvidia nvidia-utils libva-vdpau-driver nvidia-settings amd-ucode lib32-nvidia-utils lib32-opencl-nvidia opencl-nvidia --noconfirm
