#!/bin/bash

pacman -S yay --noconfirm
yay -Syu 
yay 
yay -S update-grub ly xterm hyprland-nvidia foot icewm volumeicon dmenu midori qtfm leafpad qt6-wayland qt5-wayland wofi feh noto-fonts pavucontrol file-roller opencl-nvidia unrar p7zip xdg-desktop-portal-hyprland nohang --noconfirm
yay -S nvidia-tweaks --noconfirm
yay -S polkit-dumb-agent-git 

yay --save --devel

mkinitcpio -P

