#!/bin/bash

pacman -S yay --noconfirm
yay -Syu 
yay -S update-grub ly xterm hyprland-nvidia icewm firefox qtfm leafpad qt6-wayland qt5-wayland wofi feh pavucontrol file-roller opencl-nvidia unrar p7zip xdg-desktop-portal-hyprland --noconfirm
yay -S polkit-dumb-agent-git 
yay -S havoc
yay -S nvidia-tweaks
