#!/bin/bash

pacman -S yay --noconfirm
yay -Syu 
yay 
yay -S update-grub ly xterm hyprland-nvidia foot icewm dmenu midori qtfm leafpad qt6-wayland qt5-wayland wofi feh noto-fonts pavucontrol file-roller opencl-nvidia unrar p7zip xdg-desktop-portal-hyprland --noconfirm
yay -S polkit-dumb-agent-git 
yay -S nvidia-tweaks
