#!/bin/bash



echo 'Section "InputClass"
	Identifier "My Mouse"
	Driver "libinput"
	MatchIsPointer "yes"
	Option "AccelProfile" "flat"
	Option "AccelSpeed" "0"
EndSection
' >> /usr/share/X11/xorg.conf.d/50-mouse-acceleration.conf


yay -S nvidia-force-comp-pipeline
